### ISSUE TITLE
syslog router preprocessor: crash

### ISSUE THREAD

**Issue by kris-watts-gravwell** [gravwell/gravwell#1248]
## What are the steps to reproduce this issue?

1. unknown

## What happens?

crash

## What were you expecting to happen?

not crash

## Any logs, error output, etc?

```
goroutine 41 [running]:
github.com/gravwell/syslogparser.DetectRFC({0xc00035aab0?, 0xc00049c420?, 0x20?})
    github.com/gravwell/syslogparser@v0.0.0-20230331221307-ab77654a9657/syslogparser.go:36 +0x97
github.com/gravwell/gravwell/v3/ingest/processors.crackData({0xc00035aab0, 0x8, 0x8})
    github.com/gravwell/gravwell/v3/ingest/processors/syslogrouter.go:129 +0x3a
github.com/gravwell/gravwell/v3/ingest/processors.(*SyslogRouter).Process(0xc00051e3c0, {0xc000068470, 0x1, 0xdf5200?})
    github.com/gravwell/gravwell/v3/ingest/processors/syslogrouter.go:108 +0xac
github.com/gravwell/gravwell/v3/ingest/processors.(*ProcessorSet).processItems(0xc00032ac60, {0xc000068470?, 0x8?, 0x8?})
    github.com/gravwell/gravwell/v3/ingest/processors/processors.go:425 +0x8a
github.com/gravwell/gravwell/v3/ingest/processors.(*ProcessorSet).ProcessContext(0xc00032ac60, 0xc0001ba1c0, {0x1127738, 0xc00037c460})
    github.com/gravwell/gravwell/v3/ingest/processors/processors.go:376 +0xe5
main.rfc5424ConnHandlerTCP({0x112c408?, 0xc0003ee530}, {{0xc000319840, 0xa}, 0xc, 0x7, 0x0, 0x1, 0x0, {0x0, ...}, ...})
    github.com/gravwell/gravwell/v3/ingesters/SimpleRelay/rfc5424Handlers.go:122 +0xa6d
created by main.acceptor in goroutine 65
    github.com/gravwell/gravwell/v3/ingesters/SimpleRelay/simple.go:187 +0x759
```

## Any other comments?

happened a few times

```
goroutine 6 [running]:
github.com/gravwell/syslogparser.DetectRFC({0xc00032be68?, 0xc000744960?, 0x20?})
    github.com/gravwell/syslogparser@v0.0.0-20230331221307-ab77654a9657/syslogparser.go:36 +0x97
github.com/gravwell/gravwell/v3/ingest/processors.crackData({0xc00032be68, 0x4, 0x8})
    github.com/gravwell/gravwell/v3/ingest/processors/syslogrouter.go:129 +0x3a
github.com/gravwell/gravwell/v3/ingest/processors.(*SyslogRouter).Process(0xc00046e600, {0xc000120750, 0x1, 0xdf5200?})
    github.com/gravwell/gravwell/v3/ingest/processors/syslogrouter.go:108 +0xac
github.com/gravwell/gravwell/v3/ingest/processors.(*ProcessorSet).processItems(0xc000493410, {0xc000120750?, 0x8?, 0x8?})
    github.com/gravwell/gravwell/v3/ingest/processors/processors.go:425 +0x8a
github.com/gravwell/gravwell/v3/ingest/processors.(*ProcessorSet).ProcessContext(0xc000493410, 0xc0004dff10, {0x1127738, 0xc00009a320})
    github.com/gravwell/gravwell/v3/ingest/processors/processors.go:376 +0xe5
main.rfc5424ConnHandlerTCP({0x112c408?, 0xc0001207d0}, {{0xc00033b7e0, 0xa}, 0xc, 0x7, 0x0, 0x1, 0x0, {0x0, ...}, ...})
    github.com/gravwell/gravwell/v3/ingesters/SimpleRelay/rfc5424Handlers.go:122 +0xa6d
created by main.acceptor in goroutine 48
    github.com/gravwell/gravwell/v3/ingesters/SimpleRelay/simple.go:187 +0x759
```

```
goroutine 73 [running]:
github.com/gravwell/syslogparser.DetectRFC({0xc000319b90?, 0xc000505760?, 0x20?})
    github.com/gravwell/syslogparser@v0.0.0-20230331221307-ab77654a9657/syslogparser.go:36 +0x97
github.com/gravwell/gravwell/v3/ingest/processors.crackData({0xc000319b90, 0x7, 0x8})
    github.com/gravwell/gravwell/v3/ingest/processors/syslogrouter.go:129 +0x3a
github.com/gravwell/gravwell/v3/ingest/processors.(*SyslogRouter).Process(0xc0006300c0, {0xc000b82190, 0x1, 0xdf5200?})
    github.com/gravwell/gravwell/v3/ingest/processors/syslogrouter.go:108 +0xac
github.com/gravwell/gravwell/v3/ingest/processors.(*ProcessorSet).processItems(0xc00032a2d0, {0xc000b82190?, 0x8?, 0x8?})
    github.com/gravwell/gravwell/v3/ingest/processors/processors.go:425 +0x8a
github.com/gravwell/gravwell/v3/ingest/processors.(*ProcessorSet).ProcessContext(0xc00032a2d0, 0xc0006e8230, {0x1127738, 0xc0003f42d0})
    github.com/gravwell/gravwell/v3/ingest/processors/processors.go:376 +0xe5
main.rfc5424ConnHandlerTCP({0x112c408?, 0xc000b82088}, {{0xc000319840, 0xa}, 0xc, 0x7, 0x0, 0x1, 0x0, {0x0, ...}, ...})
    github.com/gravwell/gravwell/v3/ingesters/SimpleRelay/rfc5424Handlers.go:122 +0xa6d
created by main.acceptor in goroutine 84
    github.com/gravwell/gravwell/v3/ingesters/SimpleRelay/simple.go:187 +0x759
```

## What versions of software are you using?

5.5.0

**Comment by david-fritz-gravwell** [comment]
There just isn't a bounds check there at all:

https://github.com/gravwell/syslogparser/blob/1b31d9cb1c977cd056ec07b066807080fdead4f2/syslogparser.go#L36

**Comment by kris-watts-gravwell** [comment]
> There just isn't a bounds check there at all:
> 
> https://github.com/gravwell/syslogparser/blob/1b31d9cb1c977cd056ec07b066807080fdead4f2/syslogparser.go#L36

well that's just comically bad.

**Comment by kris-watts-gravwell** [comment]
i'll put in something to guard us and then get a PR fired upstream

**Comment by kris-watts-gravwell** [comment]
5.6.0-beta2 LGTM
